/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package michaelmartinez_lab9p2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Michael Martínez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        HiloFecha nuevoHilo= new HiloFecha(jl_fecha, jl_hora);
        Thread proceso=new Thread(nuevoHilo);
        proceso.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBlanco = new javax.swing.JPanel();
        labelBienvenido = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jl_fecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jl_hora = new javax.swing.JLabel();
        panelRojo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jb_subirArchivo = new javax.swing.JButton();
        labelSubirArchivo = new javax.swing.JLabel();
        pb_barraProgreso = new javax.swing.JProgressBar();
        labelArchivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_TextArea = new javax.swing.JTextArea();
        jb_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelBienvenido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        labelBienvenido.setText("BIENVENIDO");
        labelBienvenido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 0, 0));
        labelFecha.setText("FECHA DE HOY");

        jl_fecha.setBackground(new java.awt.Color(255, 153, 255));
        jl_fecha.setForeground(new java.awt.Color(0, 0, 0));

        labelHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHora.setForeground(new java.awt.Color(0, 0, 0));
        labelHora.setText("HORA ACTUAL");

        jl_hora.setBackground(new java.awt.Color(255, 204, 204));
        jl_hora.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelBlancoLayout.createSequentialGroup()
                            .addComponent(labelBienvenido)
                            .addContainerGap(129, Short.MAX_VALUE))
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFecha)
                            .addComponent(labelHora)))
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelBienvenido)
                .addGap(64, 64, 64)
                .addComponent(labelFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRojo.setBackground(new java.awt.Color(255, 51, 51));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("BOROA CLOUD");

        jb_subirArchivo.setText("SUBIR ARCHIVO");
        jb_subirArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_subirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_subirArchivoMouseClicked(evt);
            }
        });

        labelSubirArchivo.setText("Subiendo archivo");

        pb_barraProgreso.setBackground(new java.awt.Color(255, 255, 255));

        labelArchivo.setText("ARCHIVO");

        ta_TextArea.setBackground(new java.awt.Color(255, 153, 153));
        ta_TextArea.setColumns(20);
        ta_TextArea.setForeground(new java.awt.Color(0, 0, 0));
        ta_TextArea.setRows(5);
        jScrollPane1.setViewportView(ta_TextArea);

        jb_guardar.setText("GUARDAR");
        jb_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRojoLayout = new javax.swing.GroupLayout(panelRojo);
        panelRojo.setLayout(panelRojoLayout);
        panelRojoLayout.setHorizontalGroup(
            panelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRojoLayout.createSequentialGroup()
                .addGroup(panelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRojoLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jb_subirArchivo))
                    .addGroup(panelRojoLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(labelArchivo))
                    .addGroup(panelRojoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelSubirArchivo)
                                .addComponent(pb_barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRojoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_guardar)
                .addGap(144, 144, 144))
        );
        panelRojoLayout.setVerticalGroup(
            panelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRojoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jb_subirArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSubirArchivo)
                .addGap(18, 18, 18)
                .addComponent(pb_barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelArchivo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_guardar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_subirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_subirArchivoMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc=new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivos de texto", "txt");
        jfc.setFileFilter(filtro);
        int seleccion=jfc.showSaveDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            String nombre = jfc.getSelectedFile().getName();
            if (nombre.contains(".txt")) {
                File file = jfc.getSelectedFile();
                archivo=file;
                hiloBarra hiloBarra = new hiloBarra(pb_barraProgreso, ta_TextArea,file);
                Thread proceso2 = new Thread(hiloBarra);
                proceso2.start();
            }
        }
        

    }//GEN-LAST:event_jb_subirArchivoMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        FileWriter fw=null;
        try {
            // TODO add your handling code here:
            fw = new FileWriter(archivo);
            System.out.println(archivo.getPath());
            BufferedWriter bw=new BufferedWriter(fw);
            bw.write(ta_TextArea.getText());
            ta_TextArea.setText("");
            bw.flush();
            fw.close();
            bw.close();
            JOptionPane.showMessageDialog(this, "Archivo modificado");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
                
    }//GEN-LAST:event_jb_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
private File archivo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_subirArchivo;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JLabel labelArchivo;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelSubirArchivo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelRojo;
    private javax.swing.JProgressBar pb_barraProgreso;
    private javax.swing.JTextArea ta_TextArea;
    // End of variables declaration//GEN-END:variables
}
